FROM node:16.19.1-alpine

# RUN addgroup -S appgroup && adduser -S app -G appgroup

ARG NEXT_PUBLIC_API_BASE_URL=NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ARG DATABASE_URL=DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
ARG NEXT_PUBLIC_BASE_PATH=NEXT_PUBLIC_BASE_PATH
ENV NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}

WORKDIR /home/app
COPY . .
RUN npm install --force
RUN npm run build

EXPOSE 3000
# USER app

CMD [ "npm","run","start-s" ]