apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.client.app }}
  namespace: {{ .Release.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: {{ .Values.client.app }}
    project: {{ .Values.project }}
spec:
  {{- with .Values.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end}}
  {{- if eq .Values.client.ingress.useTls "true" }}
  tls:
  {{- if eq .Values.client.ingress.useHost "true"  }}
  - hosts: 
    - {{ .Values.client.ingress.host }}
    secretName: {{ .Values.client.ingress.tls }}
  {{- else}}
  - secretName: {{ .Values.client.ingress.tls }}
  {{- end}}
  {{- end}}
  rules:
  {{- if eq .Values.client.ingress.useHost "true" }}
  - host: {{ .Values.client.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.client.ingress.path }}
        backend:
          service:
            name: {{ .Values.client.app }}
            port: 
              number: {{ .Values.client.service.port }}
  {{- else }}
  - http:
        paths:
          - path: {{ .Values.client.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.client.app }}
                port:
                  number: {{ .Values.client.service.port }}
  {{- end}}